#!/bin/bash

gnuplot -persist <<-EOFMarker
	set term png 
	set grid 
	set title "Convergence of Residual Norm" 
	set xlabel "number of iterations"
	set ylabel " absolute residual norm"
	set logscale y 10
    set key autotitle columnhead
	set output "residual_norms.png" 
	plot "rnorm_Serena_petsc_gmres_gamg.txt" using 1:2 with lines lw 2
EOFMarker